name: Build and Deploy

on:
  push:
    branches: ["main"]

env:
  ENVS: "envs"

# for AWS credentials
permissions:
  id-token: write
  contents: read

jobs:
  publish-docker-image-to-aws-ecr:
    runs-on: ubuntu-latest
    environment: main
    steps:
      # checkout branch
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CONNECT_ARN }}
          aws-region: ap-northeast-2

      - name: login to AWS ECR
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-to-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --build-arg ACTIVE_PROFILES=${{ vars.PROFILE }} .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
